# Generated by Django 3.0.8 on 2020-08-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskdocumentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracomment',
            name='system_action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not system'), (1, 'Confused'), (2, 'Completed')], default=0, verbose_name='System action'),
        ),
    ]
